language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=4.2.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=4.3.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=4.4.*@dev
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*@dev
    - php: 7.2
      env: SYMFONY_VERSION=4.2.*@dev
    - php: 7.2
      env: SYMFONY_VERSION=4.3.*@dev
    - php: 7.2
      env: SYMFONY_VERSION=4.4.*@dev
    - php: 7.3
      env: SYMFONY_VERSION=4.2.*@dev
    - php: 7.3
      env: SYMFONY_VERSION=4.3.*@dev
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*@dev
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*@dev
    - php: 7.4
      env: SYMFONY_VERSION=4.4.*@dev
    - php: 7.4
      env: SYMFONY_VERSION=5.0.*@dev

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/http-kernel:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/validator:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/form:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ] && [ "$SYMFONY_VERSION" == "4.3.*" ]; then composer require "codeclimate/php-test-reporter:dev-master@dev" --no-update; fi;

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ] && [ "$SYMFONY_VERSION" == "4.3.*" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi;

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ] && [ "$SYMFONY_VERSION" == "4.3.*" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
