language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
  include:
    - php: 5.4
      env: SYMFONY_VERSION=2.7.*@dev
    - php: 5.5
      env: SYMFONY_VERSION=2.7.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=3.3.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=3.4.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=4.0.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=3.0.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*@dev

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - composer config minimum-stability dev
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/http-kernel:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/validator:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/form:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require "codeclimate/php-test-reporter:dev-master@dev" --no-update; fi;

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi;

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
